### ISSUE TITLE
AbstractAxisArray?

### ISSUE THREAD

**Issue by cmichelenstrofer** [JuliaArrays/AxisArrays.jl#208] opened 2022-04-25 05:14 UTC
Would an AbstractAxisArray make sense? I would personally like to create my own custom types that have fixed dimension and axis names. And create plot recipes and other functions on these custom types. While being able to "inherit" all the functionalities of AxisArrays. I'm aware of python projects that subclass xarray in this way.

**Comment by LilithHafner** [comment] 2022-11-13 08:08
Duplicate of #106

**Closed** 2023-07-03 22:56 UTC
